-- =============================================
-- 03_WAREHOUSE_MANAGEMENT.SQL
-- Healthcare RxDecision Analytics Platform
-- Cost-Optimized Warehouse Configuration
-- =============================================

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS HC_ETL_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE COMMENT = 'Healthcare RxDecision - ETL Processing';

CREATE WAREHOUSE IF NOT EXISTS HC_TRANSFORM_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE COMMENT = 'Healthcare RxDecision - Data Transformation';

CREATE WAREHOUSE IF NOT EXISTS HC_ANALYTICS_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE COMMENT = 'Healthcare RxDecision - Analytics Queries';

CREATE WAREHOUSE IF NOT EXISTS HC_AI_WH
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE COMMENT = 'Healthcare RxDecision - AI/ML Workloads';

USE ROLE ACCOUNTADMIN;
GRANT USAGE ON WAREHOUSE HC_ETL_WH TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE HC_TRANSFORM_WH TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE HC_ANALYTICS_WH TO ROLE HC_ANALYST;
GRANT USAGE ON WAREHOUSE HC_AI_WH TO ROLE HC_DATA_SCIENTIST;

SHOW WAREHOUSES LIKE 'HC_%';
