-- =============================================
-- 04_DATABASE_STRUCTURE.SQL
-- Healthcare RxDecision Analytics Platform
-- Medallion Architecture + Marketplace Integration
-- =============================================

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS RAW_DB COMMENT = 'Bronze Layer - Raw Data + Marketplace Ingestion';
CREATE SCHEMA IF NOT EXISTS RAW_DB.RAW_SCHEMA;

CREATE DATABASE IF NOT EXISTS TRANSFORM_DB COMMENT = 'Silver Layer - Cleaned & Transformed Data';
CREATE SCHEMA IF NOT EXISTS TRANSFORM_DB.TRANSFORM_SCHEMA;

CREATE DATABASE IF NOT EXISTS ANALYTICS_DB COMMENT = 'Gold Layer - Analytics Ready';
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB.ANALYTICS_SCHEMA;

CREATE DATABASE IF NOT EXISTS AI_READY_DB COMMENT = 'Platinum Layer - AI/ML Ready';
CREATE SCHEMA IF NOT EXISTS AI_READY_DB.AI_SCHEMA;
CREATE SCHEMA IF NOT EXISTS AI_READY_DB.FEATURE_STORE COMMENT = 'ML Feature Store';
CREATE SCHEMA IF NOT EXISTS AI_READY_DB.SEMANTIC_MODELS COMMENT = 'Cortex Analyst Semantic Models';

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS MONITORING_DB COMMENT = 'Monitoring and Observability';
CREATE SCHEMA IF NOT EXISTS MONITORING_DB.MONITORING_SCHEMA;
CREATE DATABASE IF NOT EXISTS DEVOPS_DB COMMENT = 'DevOps and CI/CD';
CREATE SCHEMA IF NOT EXISTS DEVOPS_DB.CI_CD;
CREATE DATABASE IF NOT EXISTS AUDIT_DB COMMENT = 'Audit and Compliance';
CREATE SCHEMA IF NOT EXISTS AUDIT_DB.AUDIT_SCHEMA;
CREATE DATABASE IF NOT EXISTS SECURITY_DB COMMENT = 'Security Policies';
CREATE SCHEMA IF NOT EXISTS SECURITY_DB.POLICIES;
CREATE DATABASE IF NOT EXISTS GOVERNANCE_DB COMMENT = 'Data Governance Tags & Policies';
CREATE SCHEMA IF NOT EXISTS GOVERNANCE_DB.TAGS;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE_DB.POLICIES;
CREATE DATABASE IF NOT EXISTS INTEGRATIONS_DB COMMENT = 'External Integrations (GitHub)';
CREATE SCHEMA IF NOT EXISTS INTEGRATIONS_DB.GIT;

GRANT USAGE ON DATABASE RAW_DB TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON DATABASE TRANSFORM_DB TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE HC_ANALYST;
GRANT USAGE ON DATABASE AI_READY_DB TO ROLE HC_DATA_SCIENTIST;
GRANT ALL ON SCHEMA RAW_DB.RAW_SCHEMA TO ROLE HC_DATA_ENGINEER;
GRANT ALL ON SCHEMA TRANSFORM_DB.TRANSFORM_SCHEMA TO ROLE HC_DATA_ENGINEER;
GRANT ALL ON SCHEMA ANALYTICS_DB.ANALYTICS_SCHEMA TO ROLE HC_ANALYST;

SHOW DATABASES LIKE '%_DB';
