-- =============================================
-- 05_RESOURCE_MONITORS.SQL
-- Healthcare RxDecision Analytics Platform
-- Cost Management
-- =============================================

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR HC_ETL_WH_MONITOR
    WITH CREDIT_QUOTA = 10 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE RESOURCE MONITOR HC_TRANSFORM_WH_MONITOR
    WITH CREDIT_QUOTA = 10 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE RESOURCE MONITOR HC_ANALYTICS_WH_MONITOR
    WITH CREDIT_QUOTA = 10 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE RESOURCE MONITOR HC_AI_WH_MONITOR
    WITH CREDIT_QUOTA = 10 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE RESOURCE MONITOR HC_ACCOUNT_MONITOR
    WITH CREDIT_QUOTA = 50 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 50 PERCENT DO NOTIFY ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE HC_ETL_WH SET RESOURCE_MONITOR = HC_ETL_WH_MONITOR;
ALTER WAREHOUSE HC_TRANSFORM_WH SET RESOURCE_MONITOR = HC_TRANSFORM_WH_MONITOR;
ALTER WAREHOUSE HC_ANALYTICS_WH SET RESOURCE_MONITOR = HC_ANALYTICS_WH_MONITOR;
ALTER WAREHOUSE HC_AI_WH SET RESOURCE_MONITOR = HC_AI_WH_MONITOR;

SHOW RESOURCE MONITORS LIKE 'HC_%';
