-- =============================================
-- 06_MONITORING_VIEWS.SQL
-- Healthcare RxDecision Analytics Platform
-- Monitoring & Observability
-- =============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE MONITORING_DB;
USE SCHEMA MONITORING_SCHEMA;

CREATE OR REPLACE VIEW QUERY_HISTORY_VIEW AS
SELECT QUERY_ID, QUERY_TEXT, USER_NAME, ROLE_NAME, WAREHOUSE_NAME, EXECUTION_STATUS,
       START_TIME, END_TIME, TOTAL_ELAPSED_TIME, BYTES_SCANNED, ROWS_PRODUCED
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE);

CREATE OR REPLACE VIEW LOGIN_HISTORY_VIEW AS
SELECT EVENT_TIMESTAMP, USER_NAME, CLIENT_IP, IS_SUCCESS, ERROR_CODE
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE EVENT_TIMESTAMP >= DATEADD(DAY, -30, CURRENT_DATE);

CREATE OR REPLACE VIEW FAILED_LOGINS_VIEW AS
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE IS_SUCCESS = 'NO' AND EVENT_TIMESTAMP >= DATEADD(DAY, -7, CURRENT_DATE);

CREATE OR REPLACE VIEW LONG_RUNNING_QUERIES_VIEW AS
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE TOTAL_ELAPSED_TIME > 300000 AND START_TIME >= DATEADD(DAY, -7, CURRENT_DATE);

CREATE OR REPLACE VIEW CREDIT_USAGE_VIEW AS
SELECT WAREHOUSE_NAME, DATE_TRUNC('DAY', START_TIME) AS USAGE_DATE, SUM(CREDITS_USED) AS DAILY_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE)
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('DAY', START_TIME);

CREATE OR REPLACE VIEW WAREHOUSE_LOAD_HISTORY_VIEW AS
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY;

CREATE OR REPLACE VIEW BLOCKED_QUERIES_VIEW AS
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE ERROR_CODE IS NOT NULL;

CREATE OR REPLACE VIEW STORAGE_USAGE_VIEW AS
SELECT USAGE_DATE, STORAGE_BYTES, STAGE_BYTES, FAILSAFE_BYTES
FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE
WHERE USAGE_DATE >= DATEADD(DAY, -30, CURRENT_DATE);

SHOW VIEWS IN MONITORING_DB.MONITORING_SCHEMA;
