-- =============================================
-- 08_DATA_GOVERNANCE.SQL
-- Healthcare RxDecision Analytics Platform
-- Data Governance & HIPAA Compliance
-- =============================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS GOVERNANCE_DB;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE_DB.TAGS;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE_DB.POLICIES;

USE DATABASE GOVERNANCE_DB;
USE SCHEMA TAGS;

CREATE OR REPLACE TAG DATA_CLASSIFICATION
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'
    COMMENT = 'Data classification level';

CREATE OR REPLACE TAG PII_TYPE
    ALLOWED_VALUES 'SSN', 'PHONE', 'EMAIL', 'ADDRESS', 'DOB', 'NAME'
    COMMENT = 'Personally Identifiable Information type';

CREATE OR REPLACE TAG PHI_TYPE
    ALLOWED_VALUES 'DIAGNOSIS', 'TREATMENT', 'LAB_RESULTS', 'VITALS', 'MEDICATIONS'
    COMMENT = 'Protected Health Information type';

USE SCHEMA POLICIES;

CREATE OR REPLACE MASKING POLICY SSN_MASK AS (VAL STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'HC_ACCOUNT_ADMIN', 'HC_DATA_ENGINEER') THEN VAL
         ELSE '***-**-' || RIGHT(VAL, 4) END;

CREATE OR REPLACE MASKING POLICY PHONE_MASK AS (VAL STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'HC_ACCOUNT_ADMIN', 'HC_DATA_ENGINEER') THEN VAL
         ELSE '***-***-' || RIGHT(VAL, 4) END;

CREATE OR REPLACE MASKING POLICY INSURANCE_MASK AS (VAL STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'HC_ACCOUNT_ADMIN') THEN VAL
         ELSE LEFT(VAL, 3) || '****' || RIGHT(VAL, 2) END;

CREATE OR REPLACE ROW ACCESS POLICY REGION_ACCESS AS (REGION_COL STRING) RETURNS BOOLEAN ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'HC_ACCOUNT_ADMIN') THEN TRUE
         WHEN CURRENT_ROLE() = 'HC_DATA_ENGINEER' AND REGION_COL IN ('US', 'EU') THEN TRUE
         WHEN CURRENT_ROLE() = 'HC_ANALYST' AND REGION_COL = 'US' THEN TRUE
         ELSE FALSE END;

SHOW TAGS IN GOVERNANCE_DB.TAGS;
SHOW MASKING POLICIES IN GOVERNANCE_DB.POLICIES;
