-- =============================================
-- 09_AUDIT_LAYER.SQL
-- Healthcare RxDecision Analytics Platform
-- Audit & Compliance
-- =============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE AUDIT_DB;
USE SCHEMA AUDIT_SCHEMA;

CREATE OR REPLACE VIEW ACCESS_HISTORY_VIEW AS
SELECT ah.QUERY_START_TIME, ah.USER_NAME, qh.ROLE_NAME, ah.DIRECT_OBJECTS_ACCESSED, ah.BASE_OBJECTS_ACCESSED, ah.OBJECTS_MODIFIED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah
JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY qh ON ah.QUERY_ID = qh.QUERY_ID
WHERE ah.QUERY_START_TIME >= DATEADD(DAY, -30, CURRENT_DATE);

CREATE OR REPLACE VIEW DATA_CHANGES_AUDIT AS
SELECT QUERY_ID, QUERY_TEXT, USER_NAME, ROLE_NAME, DATABASE_NAME, SCHEMA_NAME, QUERY_TYPE, START_TIME,
       ROWS_PRODUCED, ROWS_UPDATED, ROWS_DELETED, ROWS_INSERTED
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TYPE IN ('INSERT', 'UPDATE', 'DELETE', 'MERGE', 'TRUNCATE_TABLE')
AND START_TIME >= DATEADD(DAY, -30, CURRENT_DATE);

CREATE OR REPLACE VIEW ROLE_GRANTS_AUDIT AS
SELECT CREATED_ON, MODIFIED_ON, PRIVILEGE, GRANTED_ON, NAME, TABLE_CATALOG, TABLE_SCHEMA,
       GRANTED_TO, GRANTEE_NAME, GRANT_OPTION, GRANTED_BY
FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES
WHERE CREATED_ON >= DATEADD(DAY, -90, CURRENT_DATE);

CREATE OR REPLACE VIEW USER_LOGIN_AUDIT AS
SELECT EVENT_TIMESTAMP, USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE, FIRST_AUTHENTICATION_FACTOR,
       IS_SUCCESS, ERROR_CODE, ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE EVENT_TIMESTAMP >= DATEADD(DAY, -30, CURRENT_DATE);

CREATE OR REPLACE VIEW SENSITIVE_DATA_ACCESS AS
SELECT ah.QUERY_START_TIME, ah.USER_NAME, qh.ROLE_NAME, qh.QUERY_TEXT, ah.DIRECT_OBJECTS_ACCESSED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah
JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY qh ON ah.QUERY_ID = qh.QUERY_ID
WHERE ah.QUERY_START_TIME >= DATEADD(DAY, -7, CURRENT_DATE)
AND (LOWER(qh.QUERY_TEXT) LIKE '%patient%' OR LOWER(qh.QUERY_TEXT) LIKE '%ssn%');

CREATE OR REPLACE VIEW COMPLIANCE_SUMMARY AS
SELECT 'Total Queries' AS METRIC, COUNT(*) AS VALUE
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE)
UNION ALL
SELECT 'Failed Logins', COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE IS_SUCCESS = 'NO' AND EVENT_TIMESTAMP >= DATEADD(DAY, -30, CURRENT_DATE)
UNION ALL
SELECT 'Data Modifications', COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TYPE IN ('INSERT', 'UPDATE', 'DELETE') AND START_TIME >= DATEADD(DAY, -30, CURRENT_DATE);

SHOW VIEWS IN AUDIT_DB.AUDIT_SCHEMA;
