-- =============================================
-- 10_VERIFICATION.SQL
-- Healthcare RxDecision Analytics Platform
-- Deployment Verification
-- =============================================

USE ROLE ACCOUNTADMIN;

SELECT 'PATIENT_RAW' AS TABLE_NAME, 'BRONZE' AS LAYER, COUNT(*) AS ROW_COUNT FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW
UNION ALL SELECT 'ICU_EVENTS','BRONZE',COUNT(*) FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS
UNION ALL SELECT 'BILLING_DATA','BRONZE',COUNT(*) FROM RAW_DB.RAW_SCHEMA.BILLING_DATA
UNION ALL SELECT 'HOSPITALS','BRONZE',COUNT(*) FROM RAW_DB.RAW_SCHEMA.HOSPITALS
UNION ALL SELECT 'HCO_LOCATIONS','BRONZE',COUNT(*) FROM RAW_DB.RAW_SCHEMA.HCO_LOCATIONS
UNION ALL SELECT 'PROVIDER_AFFILIATIONS','BRONZE',COUNT(*) FROM RAW_DB.RAW_SCHEMA.PROVIDER_AFFILIATIONS
UNION ALL SELECT 'PRESCRIPTION_DATA','BRONZE',COUNT(*) FROM RAW_DB.RAW_SCHEMA.PRESCRIPTION_DATA
UNION ALL SELECT 'DEVICE_ALERTS','BRONZE',COUNT(*) FROM RAW_DB.RAW_SCHEMA.DEVICE_ALERTS
UNION ALL SELECT 'MEDICATION_RECORDS','BRONZE',COUNT(*) FROM RAW_DB.RAW_SCHEMA.MEDICATION_RECORDS
UNION ALL SELECT 'CLEAN_PATIENT','SILVER',COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT
UNION ALL SELECT 'CLEAN_ICU_EVENTS','SILVER',COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS
UNION ALL SELECT 'PATIENT_ANALYTICS','GOLD',COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS
UNION ALL SELECT 'BILLING_ANALYTICS','GOLD',COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.BILLING_ANALYTICS
UNION ALL SELECT 'ICU_FEATURE_STORE','PLATINUM',COUNT(*) FROM AI_READY_DB.FEATURE_STORE.ICU_FEATURE_STORE
UNION ALL SELECT 'PATIENT_NOTES','PLATINUM',COUNT(*) FROM AI_READY_DB.FEATURE_STORE.PATIENT_NOTES
UNION ALL SELECT 'PATIENT_EMBEDDINGS','PLATINUM',COUNT(*) FROM AI_READY_DB.FEATURE_STORE.PATIENT_EMBEDDINGS
ORDER BY LAYER, TABLE_NAME;

SHOW DATABASES LIKE '%_DB';
SET db_count = (SELECT COUNT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

SHOW ROLES LIKE 'HC_%';
SET role_count = (SELECT COUNT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

SHOW WAREHOUSES LIKE 'HC_%';
SET wh_count = (SELECT COUNT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));

SELECT 
    'Databases' AS OBJECT_TYPE, $db_count AS ACTUAL_COUNT, 10 AS EXPECTED_COUNT,
    CASE WHEN $db_count >= 10 THEN 'PASS' ELSE 'FAIL' END AS STATUS
UNION ALL
SELECT 'Roles', $role_count, 6,
    CASE WHEN $role_count >= 6 THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'Warehouses', $wh_count, 4,
    CASE WHEN $wh_count >= 4 THEN 'PASS' ELSE 'FAIL' END;
